-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 07:50:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_gestionPedidosOnline_2024
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_gestionPedidosOnline_2024` ;

-- -----------------------------------------------------
-- Schema DB_gestionPedidosOnline_2024
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_gestionPedidosOnline_2024` DEFAULT CHARACTER SET utf8 ;
USE `DB_gestionPedidosOnline_2024` ;

-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`client` (
  `id_client` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_client` VARCHAR(100) NOT NULL DEFAULT 'nombre_cliente',
  `pass_client` VARCHAR(5) NOT NULL,
  `location_client` VARCHAR(45) NULL DEFAULT 'localidad_cliente',
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_client` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`product` (
  `id_product` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_product` VARCHAR(100) NOT NULL DEFAULT 'nombre_producto',
  `price_product` FLOAT UNSIGNED NOT NULL DEFAULT 0.0,
  `discount_product` INT UNSIGNED NULL DEFAULT 0,
  `season_product` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_product` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`shop` (
  `id_shop` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_shop` VARCHAR(100) NOT NULL DEFAULT 'nombre_tienda',
  `location_shop` VARCHAR(45) NULL DEFAULT 'localidad_tienda',
  `pass_shop` VARCHAR(5) NOT NULL,
  `type_shop` VARCHAR(45) NOT NULL DEFAULT 'general',
  PRIMARY KEY (`id_shop`),
  UNIQUE INDEX `id_tienda_UNIQUE` (`id_shop` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`producer` (
  `id_producer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_producer` VARCHAR(100) NOT NULL DEFAULT 'nombre_productor',
  `location_producer` VARCHAR(45) NULL DEFAULT 'localidad_productor',
  PRIMARY KEY (`id_producer`),
  UNIQUE INDEX `id_productor_UNIQUE` (`id_producer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`orders` (
  `client_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `date_order` DATE NOT NULL,
  PRIMARY KEY (`client_id`, `product_id`),
  INDEX `fk_client_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_client_has_product_client_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_product_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`sales` (
  `shop_id` INT UNSIGNED NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`shop_id`, `client_id`),
  INDEX `fk_shop_has_client_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_shop_has_client_shop1_idx` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_shop_has_client_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`shop` (`id_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_has_client_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`buys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`buys` (
  `shop_id` INT UNSIGNED NOT NULL,
  `producer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`shop_id`, `producer_id`),
  INDEX `fk_shop_has_producer_producer1_idx` (`producer_id` ASC) VISIBLE,
  INDEX `fk_shop_has_producer_shop1_idx` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_shop_has_producer_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`shop` (`id_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_has_producer_producer1`
    FOREIGN KEY (`producer_id`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`producer` (`id_producer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`productions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`productions` (
  `producer_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`producer_id`, `product_id`),
  INDEX `fk_producer_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_producer_has_product_producer1_idx` (`producer_id` ASC) VISIBLE,
  CONSTRAINT `fk_producer_has_product_producer1`
    FOREIGN KEY (`producer_id`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`producer` (`id_producer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producer_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
