-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 23:32:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_gestionPedidosOnline_2024
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_gestionPedidosOnline_2024` ;

-- -----------------------------------------------------
-- Schema DB_gestionPedidosOnline_2024
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_gestionPedidosOnline_2024` DEFAULT CHARACTER SET utf8 ;
USE `DB_gestionPedidosOnline_2024` ;

-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`user` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(100) NOT NULL,
  `pass_user` VARCHAR(5) NOT NULL,
  `location_user` VARCHAR(45) NULL,
  `type_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`product` (
  `id_product` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_product` VARCHAR(100) NOT NULL DEFAULT 'nombre_producto',
  `price_product` FLOAT UNSIGNED NOT NULL DEFAULT 0.0,
  `discount_product` INT UNSIGNED NULL DEFAULT 0,
  `season_product` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_product` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`shop` (
  `id_shop` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_shop` VARCHAR(100) NOT NULL DEFAULT 'nombre_tienda',
  `location_shop` VARCHAR(45) NULL DEFAULT 'localidad_tienda',
  `pass_shop` VARCHAR(5) NOT NULL,
  `type_shop` VARCHAR(45) NOT NULL DEFAULT 'general',
  PRIMARY KEY (`id_shop`),
  UNIQUE INDEX `id_tienda_UNIQUE` (`id_shop` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`provider` (
  `id_provider` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_provider` VARCHAR(100) NOT NULL,
  `location_provider` VARCHAR(45) NULL DEFAULT 'localidad_productor',
  PRIMARY KEY (`id_provider`),
  UNIQUE INDEX `id_productor_UNIQUE` (`id_provider` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`orders` (
  `user_id_orders` INT UNSIGNED NOT NULL,
  `product_id_orders` INT UNSIGNED NOT NULL,
  `delivery_date_orders` DATETIME NOT NULL,
  `finished_orders` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`user_id_orders`, `product_id_orders`),
  INDEX `fk_client_has_product_product1_idx` (`product_id_orders` ASC) VISIBLE,
  INDEX `fk_client_has_product_client_idx` (`user_id_orders` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_product_client`
    FOREIGN KEY (`user_id_orders`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_product_product1`
    FOREIGN KEY (`product_id_orders`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`sales` (
  `shop_id_sales` INT UNSIGNED NOT NULL,
  `user_id_sales` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`shop_id_sales`, `user_id_sales`),
  INDEX `fk_shop_has_client_client1_idx` (`user_id_sales` ASC) VISIBLE,
  INDEX `fk_shop_has_client_shop1_idx` (`shop_id_sales` ASC) VISIBLE,
  CONSTRAINT `fk_shop_has_client_shop1`
    FOREIGN KEY (`shop_id_sales`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`shop` (`id_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_has_client_client1`
    FOREIGN KEY (`user_id_sales`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`buys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`buys` (
  `shop_id_buys` INT UNSIGNED NOT NULL,
  `provider_id_buys` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`shop_id_buys`, `provider_id_buys`),
  INDEX `fk_shop_has_producer_producer1_idx` (`provider_id_buys` ASC) VISIBLE,
  INDEX `fk_shop_has_producer_shop1_idx` (`shop_id_buys` ASC) VISIBLE,
  CONSTRAINT `fk_shop_has_producer_shop1`
    FOREIGN KEY (`shop_id_buys`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`shop` (`id_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_has_producer_producer1`
    FOREIGN KEY (`provider_id_buys`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_gestionPedidosOnline_2024`.`produce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_gestionPedidosOnline_2024`.`produce` (
  `provider_id_produce` INT UNSIGNED NOT NULL,
  `product_id_produce` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`provider_id_produce`, `product_id_produce`),
  INDEX `fk_producer_has_product_product1_idx` (`product_id_produce` ASC) VISIBLE,
  INDEX `fk_producer_has_product_producer1_idx` (`provider_id_produce` ASC) VISIBLE,
  CONSTRAINT `fk_producer_has_product_producer1`
    FOREIGN KEY (`provider_id_produce`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producer_has_product_product1`
    FOREIGN KEY (`product_id_produce`)
    REFERENCES `DB_gestionPedidosOnline_2024`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
